package com.traffipart.polanty.data.remote.knowledge.dtos

import com.squareup.moshi.JsonClass

/**
 * Data Transfer Object for plant knowledge data generated by the Gemini AI.
 * This DTO represents the structured JSON schema that the AI is instructed to return.
 */
@JsonClass(generateAdapter = true)
data class GeminiPlantKnowledgeDto(
    /** The scientific name of the plant, exactly as requested in the prompt. */
    val scientificName: String,
    /** A common, recognizable name for the plant species. */
    val commonName: String,
    /** A concise botanical and care-oriented description of the plant. */
    val description: String,
    /** The native geographic origin or natural habitat of the species. */
    val origin: String,
    /** Toxicity level for pets. Expected values: NonToxic, Mild, Toxic, or Unknown. */
    val petToxicity: String,
    /** Toxicity level for humans. Expected values: NonToxic, Mild, Toxic, or Unknown. */
    val humanToxicity: String,
    /** Additional safety details, specific toxic parts, or first-aid warnings. */
    val toxicityNotes: String,
    /** The minimum typical height the plant reaches in indoor or native conditions (cm). */
    val typicalHeightCmMin: Int,
    /** The maximum typical height the plant reaches in indoor or native conditions (cm). */
    val typicalHeightCmMax: Int,
    /** The minimum number of days between soil moisture checks for watering. */
    val wateringDaysMin: Int,
    /** The maximum number of days between soil moisture checks for watering. */
    val wateringDaysMax: Int,
    /** Narrative instructions on how to water the plant and signs of thirst. */
    val wateringInstruction: String,
    /** The light requirements. Expected values: Low, MediumIndirect, BrightIndirect, or Direct. */
    val lightRequirement: String,
    /** The minimum ideal relative humidity percentage (0-100). */
    val humidityMinPercent: Int,
    /** The maximum ideal relative humidity percentage (0-100). */
    val humidityMaxPercent: Int,
    /** The minimum ideal ambient temperature in degrees Celsius (-50 to 80). */
    val temperatureMinCelsius: Double,
    /** The maximum ideal ambient temperature in degrees Celsius (-50 to 80). */
    val temperatureMaxCelsius: Double,
    /** Guidance on feeding frequency, seasonal timing, and the type of fertilizer to use. */
    val fertilizing: String,
)
